easy_admin_bundle:
    #resource: '@EasyAdminBundle/Controller/AdminController.php'
    resource: '@EasyAdminExtensionBundle/Controller/EasyAdminController.php'
    prefix: /admin
    type: annotation